### ISSUE TITLE
Unexpectedly large MIN_POSITIVE for P16 and P32

### ISSUE THREAD

**Issue by fayalalebrun** [burrbull/softposit-rs#20]
MIN_POSITIVE is defined as 0.015625 and 3.725290298_e-9, while according to the [spec](https://posithub.org/docs/posit_standard-2.pdf) it should be 6e-8 and 1.4e-17 respectively.

I have seen other software posit implementations have the same. Did the spec change at some point?

**Comment by burrbull** [comment]
This is first time I see any standard on posit.
MIN_POSITIVE is just a smallest representative value (value that corresponds to `0x1`). So the float value is depends on posit structure. It can be different for different number of fraction or exponent bits.

I didn't keep track of the situation last 2 years, so this repo is slightly abandoned.

**Comment by burrbull** [comment]
This repo implementation is based on SoftPosit.
It has (main) implementations for P8E0, P16E1, P32E2.
But specification you've linked fixes `E` size on 2 for all of them (P8E2, P16E2, P32E2).
It says (p. 3.3-3):
```
3. The exponent bit field 𝐸 has length 2 bits, but one or both bits may be beyond the LSB and thus have value
0. 𝐸 represents an integer 𝑒, its bits treated as a 2-bit unsigned integer. 0 ≤ 𝑒 ≤ 3.
```
Those are different types.

**Comment by fayalalebrun** [comment]
That clears it up, thanks for looking into it. I also found this note on their website:
```
NOTE: Contrary to the original paper by Gustafson and Yonemoto, and to early versions of the Standard,
the exponent size (eS) is always 2 and does not vary with the precision. This greatly simplifies conversions
between precisions and the creation of correctly-rounded math library functions, and in hundreds of experiments
with real applications has shown to be a better choice.
```
